name: 'Rusch & Roa'
favicon: null
layout_spectrum: 0.8025609119795263
typography_spectrum: 0.45503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5b5b5b'
    - '#cdcdcd'
    - '#989898'
    - '#e67257'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
